# Generated by Django 4.1.1 on 2022-09-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WalletService", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="fee",
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=10),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[("PAID", "PAID"), ("FAILED", "FAILED")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transfer_amount",
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=10),
        ),
    ]
